kind: pipeline
type: exec
name: flask-docker

steps:
- name: flask app build
  commands:
  - docker build -t simple-flask-app:latest .

- name: docker run
  commands:
  -  docker run -d -p 5000:5000 simple-flask-app
